server {
    listen 80;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
    root /var/www/html/;
    index index.php;

    charset utf-8;

    access_log /dev/stdout;
    error_log  /dev/stderr;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(woff2|woff)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|svg|ico|webp)$ {
        expires 30d;
        access_log off;
    }
}
